# Generated by Django 5.0.7 on 2024-07-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='movies',
            field=models.ManyToManyField(related_name='collection', to='movies.movie'),
        ),
    ]
